### ISSUE TITLE
[Feature request] Support for other dmenu compatible launchers

### ISSUE THREAD

**Issue by hvitoi** [Layerex/dmenu-bluetooth#5]
Support for other launchers that support dmenu compatibility mode. Such as: Fuzzel, Wofi, Rofi, Bemenu and so on.

For instance. With `fuzzel`, the `dmenu` command should be replaced with `fuzzel --dmenu`

An example is [networkmanager-dmenu ](https://github.com/firecat53/networkmanager-dmenu) which supports multiple dmenu backends

**Comment by Layerex** [comment]
Any suggestions?
https://github.com/Layerex/dmenu-bluetooth/blob/08071ab02990e6d1110b9594bb73a065a3fb5a53/dmenu-bluetooth#L336-L346

**Comment by hvitoi** [comment]
I like it!
However, I have a feeling that someone else is going to ask support for another xxx launcher. 
What do you think about leaving the whole dmenu command to be specified by the user? (And making it a bit simpler)

For instance:

```shell
DMENU_COMMAND="${DMENU_COMMAND:-dmenu}"
run_dmenu() {
    $DMENU_COMMAND -i -p "$DMENU_BLUETOOTH_PROMPT" "${dmenu_args[@]}"
}
```

```shell
# Run with fuzzel
DMENU_COMMAND="fuzzel --dmenu" ./dmenu-bluetooth

# Run with rofi
DMENU_COMMAND="rofi -dmenu" ./dmenu-bluetooth
```

`networkmanager-dmenu` achieves it in a similar manner, but using a config file to specific the dmenu command. Example:

```conf
# ~/.config/networkmanager-dmenu/config.ini
[dmenu]
dmenu_command = fuzzel --dmenu
compact = true
wifi_chars = ▂▄▆█

[dmenu_passphrase]
obscure = True

```

**Comment by Layerex** [comment]
> However, I have a feeling that someone else is going to ask support for another xxx launcher.

I don't mind. Anyways, refactored this a bit.

`networkmanager-dmenu` [supports individual launchers too](https://github.com/firecat53/networkmanager-dmenu/blob/265230c7ecaccf7e10f84d4414cd175f85a5b30a/networkmanager_dmenu#L96).

**Comment by octvs** [comment]
> However, I have a feeling that someone else is going to ask support for
> another xxx launcher.

Case in point: I needed a [minor tweak] to make it work with [tofi], removing
`-i` or `-p` flags. 

By the way, would it be better to pass these via `DMENU_ARGS` or set them up in
[the `case` block] instead of hard-coding on the call, so that the
aforementioned tweak is obsolete?

[minor tweak]: https://github.com/octvs/dmenu-bluetooth/commit/84db585281cbad03355b0b37415c795a251e051e
[tofi]: https://github.com/philj56/tofi
[the `case` block]: https://github.com/Layerex/dmenu-bluetooth/blob/96e2e3e1dd7ea2d2ab0c20bf21746aba8d70cc46/dmenu-bluetooth#L324-L331
